item {
  id: 1
  name: 'pepsodent'
}

item {
  id: 2
  name: 'wafers'
}

item {
  id: 3
  name: 'Bottle'
}

item {
  id: 4
  name: 'Mouse'
}

item {
  id: 5
  name: 'StickyNotepad'
}

item {
  id: 6
  name: 'OfficeMate'
}

item {
  id: 7
  name: 'Remote'
}

item {
  id: 8
  name: 'NihilentIdCard'
}

item {
  id: 9
  name: 'Colgate'
}


item {
  id: 10
  name: 'Mobile'
}