item {
  id: 1
  name: 'pepsodent'
}

item {
  id: 2
  name: 'wafers'
}

item {
  id: 3
  name: 'bottle'
}

item {
  id: 4
  name: 'mouse'
}

item {
  id: 5
  name: 'stickynote'
}

item {
  id: 6
  name: 'officemate'
}

item {
  id: 7
  name: 'remote'
}

item {
  id: 8
  name: 'nihilentidcard'
}

item {
  id: 9
  name: 'colgate'
}


item {
  id: 10
  name: 'channadal'
}